version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "TopicGRPC:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./client:/gRPC-hands-on/client
      - ./server:/gRPC-hands-on/server

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"